// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function Execute(arg1:string,arg2:Record<string, string>):Promise<any>;

export function NotifyConnectionRequest(arg1:model.PendingRequest):Promise<void>;

export function OpenExternal(arg1:string):Promise<void>;
