// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Execute(arg1, arg2) {
  return window['go']['main']['Application']['Execute'](arg1, arg2);
}

export function NotifyConnectionRequest(arg1) {
  return window['go']['main']['Application']['NotifyConnectionRequest'](arg1);
}

export function OpenExternal(arg1) {
  return window['go']['main']['Application']['OpenExternal'](arg1);
}
